"""Initial migration: users, auth tokens, chatbot queries and responses

Revision ID: cfe0d32c7b6f
Revises: 
Create Date: 2025-11-29 23:24:12.994727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe0d32c7b6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('interaction_history', sa.JSON(), nullable=True),
    sa.Column('background_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_value', sa.String(), nullable=False),
    sa.Column('expiration_timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_tokens_expiration_timestamp'), 'auth_tokens', ['expiration_timestamp'], unique=False)
    op.create_index(op.f('ix_auth_tokens_id'), 'auth_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_auth_tokens_is_active'), 'auth_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_auth_tokens_token_value'), 'auth_tokens', ['token_value'], unique=True)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('chatbot_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_queries_id'), 'chatbot_queries', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_queries_timestamp'), 'chatbot_queries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chatbot_queries_user_id'), 'chatbot_queries', ['user_id'], unique=False)
    op.create_table('chatbot_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('source_references', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['chatbot_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbot_responses_id'), 'chatbot_responses', ['id'], unique=False)
    op.create_index(op.f('ix_chatbot_responses_query_id'), 'chatbot_responses', ['query_id'], unique=True)
    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cart_pkey'))
    )
    op.drop_index(op.f('ix_chatbot_responses_query_id'), table_name='chatbot_responses')
    op.drop_index(op.f('ix_chatbot_responses_id'), table_name='chatbot_responses')
    op.drop_table('chatbot_responses')
    op.drop_index(op.f('ix_chatbot_queries_user_id'), table_name='chatbot_queries')
    op.drop_index(op.f('ix_chatbot_queries_timestamp'), table_name='chatbot_queries')
    op.drop_index(op.f('ix_chatbot_queries_id'), table_name='chatbot_queries')
    op.drop_table('chatbot_queries')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_token_value'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_is_active'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_expiration_timestamp'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###



